#include <stdio.h>
#include "main.h"

/**
*fibonacci -> fibonacci number genereted
*@n: parameter
*Return: fibonacci number
*/
long fibonacci(int n)
{
if (n == 0 || n == 1)
	return (1);
if (n == 2)
	return (2);
return (fibonacci(n - 1) + fibonacci(n - 2));
}

/**
*main -> Each new term in the Fibonacci sequence is generated by adding
*the previous two terms
*Return: always 0
*/
int main(void)
{
int i = 1, j = 0;
while (fibonacci(i) < 4000000)
{
if (i % 2 == 0)
	j += i;
}
printf("%s", j);
printf("\n");
return (0);
}
