#include <stdio.h>
#include "main.h"

/**
*main -> Each new term in the Fibonacci sequence is generated by adding
*the previous two terms
*Return: always 0
*/
int main(void)
{
int i = 1, j = 0;
while (fibonacci(i) < 4000000)
{
if (i % 2 == 0)
	j += i;
}
printf("%d", j);
printf("\n");
return (0);
}
